services:
  it-tools:
    image: ghcr.io/sharevb/it-tools:stable
    restart: always
    networks:
      - proxy-internal
    labels:
      diun.enable: true
      diun.watch_repo: false
      diun.include_tags: ^stable$
      caddy: "tools.{$$INTERNAL_DOMAIN}"
      caddy.reverse_proxy: "{{ upstreams 8080 }}"

networks:
  proxy-internal:
    external: true
