services:
  convertx:
    image: ghcr.io/c4illin/convertx:latest
    restart: always
    volumes:
      - data:/app/data
    healthcheck:
      test: curl -s -f http://localhost:3000/healthcheck -o /dev/null || exit 1
      interval: 1m30s
      timeout: 10s
      start_period: 10s
    environment:
      TZ: ${TIMEZONE:?error}
      ACCOUNT_REGISTRATION: false
      ALLOW_UNAUTHENTICATED: true
      AUTO_DELETE_EVERY_N_HOURS: 1
    networks:
      - proxy-internal
    labels:
      diun.enable: true
      diun.watch_repo: false
      diun.include_tags: ^latest$
      caddy: "{$$WILDCARD_INTERNAL}"
      caddy.import: service_proxy convert
      caddy.import.reverse_proxy: "{{ upstreams 3000 }}"
      homepage.group: Tools
      homepage.name: ConvertX
      homepage.icon: mdi-file-swap
      homepage.href: https://convert.{{HOMEPAGE_VAR_INTERNAL_DOMAIN}}
      homepage.description: File converter
      homepage.weight: 200

volumes:
  data:

networks:
  proxy-internal:
    external: true
