services:
  plausible_db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 1m
    secrets:
      - db-password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
    networks:
      - database

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.12-alpine
    restart: always
    configs:
      - source: clickhouse-logs
        target: /etc/clickhouse-server/config.d/logs.xml
      # This makes ClickHouse bind to IPv4 only, since Docker doesn't enable IPv6 in bridge networks by default.
      # Fixes "Listen [::]:9000 failed: Address family for hostname not supported" warnings.
      - source: clickhouse-ipv4-only
        target: /etc/clickhouse-server/config.d/ipv4-only.xml
      # The following configuration files make ClickHouse consume less resources, which is useful for small setups.
      # https://clickhouse.com/docs/en/operations/tips#using-less-than-16gb-of-ram
      - source: clickhouse-low-resources
        target: /etc/clickhouse-server/config.d/low-resources.xml
      - source: clickhouse-default-profile-low-resources-overrides
        target: /etc/clickhouse-server/users.d/default-profile-low-resources-overrides.xml
    volumes:
      - event-data:/var/lib/clickhouse
      - event-logs:/var/log/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 -O - http://127.0.0.1:8123/ping || exit 1"]
      start_period: 1m
    environment:
      CLICKHOUSE_SKIP_USER_SETUP: 1
    networks:
      - database

  plausible:
    image: ghcr.io/plausible/community-edition:v3
    restart: always
    command: sh -c "/entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      plausible_db:
        condition: service_healthy
      plausible_events_db:
        condition: service_healthy
    volumes:
      - plausible-data:/var/lib/plausible
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    secrets:
      - SECRET_KEY_BASE
      - MAXMIND_LICENSE_KEY
      - SMTP_USER_NAME
      - SMTP_USER_PWD
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
    environment:
      TMPDIR: /var/lib/plausible/tmp
      # Ref: https://github.com/plausible/community-edition/wiki/configuration
      BASE_URL: https://analytics.${INTERNAL_DOMAIN:?error}
      CONFIG_DIR: /run/secrets
      HTTP_PORT: 8000
      DISABLE_REGISTRATION: invite_only
      ENABLE_EMAIL_VERIFICATION: true
      DATABASE_URL: postgres://postgres:${PLAUSIBLE_DB_PASSWORD:?error}@plausible_db:5432/plausible_db
      MAXMIND_EDITION: GeoLite2-City
      MAILER_ADAPTER: Bamboo.Mua
      MAILER_EMAIL: ${SMTP_EMAIL:?error}
      MAILER_NAME: Plausible Analytics
      SMTP_HOST_ADDR: ${SMTP_HOST_ADDR:?error}
      SMTP_HOST_PORT: ${SMTP_HOST_PORT:?error}
      SMTP_HOST_SSL_ENABLED: ${SMTP_HOST_SSL_ENABLED:?error}
    networks:
      - database
      - proxy-internal
      - proxy-plausible
    labels:
      diun.enable: true
      caddy: "{$$WILDCARD_INTERNAL}"
      caddy.import: service_proxy analytics
      caddy.import.reverse_proxy: "{{ upstreams 8000 }}"
      homepage.group: Analytics
      homepage.name: Plausible
      homepage.icon: plausible
      homepage.href: https://analytics.{{HOMEPAGE_VAR_INTERNAL_DOMAIN}}
      homepage.description: Website analytics
      homepage.weight: 100

configs:
  clickhouse-logs:
    content: |
      <clickhouse>
          <logger>
              <level>warning</level>
              <console>true</console>
          </logger>

          <query_log replace="1">
              <database>system</database>
              <table>query_log</table>
              <flush_interval_milliseconds>7500</flush_interval_milliseconds>
              <engine>
                  ENGINE = MergeTree
                  PARTITION BY event_date
                  ORDER BY (event_time)
                  TTL event_date + interval 30 day
                  SETTINGS ttl_only_drop_parts=1
              </engine>
          </query_log>

          <!-- Stops unnecessary logging -->
          <metric_log remove="remove" />
          <asynchronous_metric_log remove="remove" />
          <query_thread_log remove="remove" />
          <text_log remove="remove" />
          <trace_log remove="remove" />
          <session_log remove="remove" />
          <part_log remove="remove" />
      </clickhouse>

  clickhouse-ipv4-only:
    content: |
      <clickhouse>
          <listen_host>0.0.0.0</listen_host>
      </clickhouse>

  clickhouse-low-resources:
    content: |
      <clickhouse>
          <!-- https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#mark_cache_size -->
          <mark_cache_size>524288000</mark_cache_size>
      </clickhouse>

  clickhouse-default-profile-low-resources-overrides:
    content: |
      <!-- https://clickhouse.com/docs/en/operations/tips#using-less-than-16gb-of-ram -->
      <clickhouse>
          <profiles>
              <default>
                  <!-- https://clickhouse.com/docs/en/operations/settings/settings#max_threads -->
                  <max_threads>1</max_threads>
                  <!-- https://clickhouse.com/docs/en/operations/settings/settings#max_block_size -->
                  <max_block_size>8192</max_block_size>
                  <!-- https://clickhouse.com/docs/en/operations/settings/settings#max_download_threads -->
                  <max_download_threads>1</max_download_threads>
                  <!--
                  https://clickhouse.com/docs/en/operations/settings/settings#input_format_parallel_parsing -->
                  <input_format_parallel_parsing>0</input_format_parallel_parsing>
                  <!--
                  https://clickhouse.com/docs/en/operations/settings/settings#output_format_parallel_formatting -->
                  <output_format_parallel_formatting>0</output_format_parallel_formatting>
              </default>
          </profiles>
      </clickhouse>

secrets:
  db-password:
    environment: PLAUSIBLE_DB_PASSWORD
  SECRET_KEY_BASE:
    environment: PLAUSIBLE_SECRET_KEY
  MAXMIND_LICENSE_KEY:
    environment: MAXMIND_LICENSE_KEY
  SMTP_USER_NAME:
    environment: SMTP_USER_NAME
  SMTP_USER_PWD:
    environment: SMTP_USER_PWD
  GOOGLE_CLIENT_ID:
    environment: PLAUSIBLE_GOOGLE_CLIENT_ID
  GOOGLE_CLIENT_SECRET:
    environment: PLAUSIBLE_GOOGLE_CLIENT_SECRET

volumes:
  db-data:
  event-data:
  event-logs:
  plausible-data:

networks:
  database:
    internal: true
  proxy-internal:
    external: true
  proxy-plausible:
    external: true
