services:
  mazanoke:
    image: ghcr.io/civilblur/mazanoke:latest
    restart: always
    networks:
      - proxy-internal
    labels:
      diun.enable: true
      diun.watch_repo: false
      diun.include_tags: ^latest$
      caddy: "{$$WILDCARD_INTERNAL}"
      caddy.import: service_proxy optimize
      caddy.import.reverse_proxy: "{{ upstreams 80 }}"
      homepage.group: Tools
      homepage.name: Mazanoke
      homepage.icon: mazanoke
      homepage.href: https://optimize.{{HOMEPAGE_VAR_INTERNAL_DOMAIN}}
      homepage.description: Image optimization
      homepage.weight: 200

networks:
  proxy-internal:
    external: true
